# Generated by Django 5.1.1 on 2024-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=64)),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Ingredient_table", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="FoodShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("open_hours", models.TimeField()),
                ("closing_hours", models.TimeField()),
                ("used_products", models.ManyToManyField(to="core.product")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=255)),
                (
                    "favourite_shops",
                    models.ManyToManyField(related_name="liked_by", to="core.foodshop"),
                ),
                ("ingredient_history", models.ManyToManyField(to="core.ingredient")),
                (
                    "favorite_foods",
                    models.ManyToManyField(related_name="liked_by", to="core.product"),
                ),
                ("product_history", models.ManyToManyField(to="core.product")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
