# Generated by Django 5.1 on 2024-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet_type',
            field=models.IntegerField(choices=[(0, 'Average diet'), (1, 'No meat'), (2, 'No animal products'), (3, 'no carbs'), (4, 'no new things'), (5, 'nothing apart from meat')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.IntegerField(choices=[(0, 'Free plan'), (1, 'Base tier'), (2, 'Medium tier'), (3, 'VIP plan')], default=0),
        ),
    ]
