# Generated by Django 5.1 on 2024-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_diet_type_user_subscription_plan'),
        ('nutrition_section', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='foodshop',
            name='used_products',
        ),
        migrations.AddField(
            model_name='foodshop',
            name='sold_products',
            field=models.ManyToManyField(to='nutrition_section.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_foods',
            field=models.ManyToManyField(related_name='liked_by', to='nutrition_section.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ingredient_history',
            field=models.ManyToManyField(to='nutrition_section.ingredient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_history',
            field=models.ManyToManyField(to='nutrition_section.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
