# Generated by Django 5.1 on 2024-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_ingredient_remove_foodshop_used_products_and_more'),
        ('nutrition_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshop',
            name='sold_products',
            field=models.ManyToManyField(related_name='sold_at', to='nutrition_section.product'),
        ),
    ]
