# Generated by Django 5.1 on 2024-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_foodshop_sold_products'),
        ('nutrition_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ingredient_history',
            field=models.ManyToManyField(related_name='viewed_by', to='nutrition_section.ingredient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_history',
            field=models.ManyToManyField(related_name='viewed_by', to='nutrition_section.product'),
        ),
    ]
