# Generated by Django 5.1 on 2024-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_ingredient_history_and_more'),
        ('nutrition_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_shops',
            field=models.ManyToManyField(related_name='liked_by', to='nutrition_section.ingredient'),
        ),
    ]
