# Generated by Django 5.1 on 2024-09-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_favourite_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_foods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_shops',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ingredient_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product_history',
        ),
    ]
