# Generated by Django 5.1 on 2024-09-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_favorite_foods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodshop',
            name='sold_products',
        ),
    ]
