# Generated by Django 5.1 on 2024-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_foodshop_sold_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Short_name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Safety_level', models.IntegerField(choices=[(0, 'Completely Safe'), (1, 'Moderate Risk'), (2, 'High Risk'), (3, 'No Data')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('General_description', models.TextField()),
                ('Macro_table', models.JSONField()),
            ],
        ),
    ]
