# Generated by Django 5.1.1 on 2024-10-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ingredient_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
