# Generated by Django 5.1 on 2024-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_section', '0002_product_ingredient_list_product_url'),
        ('shop_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshop',
            name='Google_Maps_Url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='foodshop',
            name='Url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='foodshop',
            name='sold_products',
            field=models.ManyToManyField(related_name='sold_at', to='nutrition_section.product'),
        ),
    ]
