# Generated by Django 5.1 on 2024-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('nutrition_section', '0001_initial'),
        ('shop_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_foods',
            field=models.ManyToManyField(related_name='liked_by', to='nutrition_section.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_shops',
            field=models.ManyToManyField(related_name='liked_by', to='shop_section.foodshop'),
        ),
        migrations.AddField(
            model_name='user',
            name='ingredient_history',
            field=models.ManyToManyField(related_name='viewed_by', to='nutrition_section.ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='product_history',
            field=models.ManyToManyField(related_name='viewed_by', to='nutrition_section.product'),
        ),
    ]
