# Generated by Django 5.1 on 2024-10-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodshop_google_maps_url_foodshop_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodShop',
        ),
    ]
