# Generated by Django 5.1 on 2024-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_foodshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_type',
            field=models.IntegerField(choices=[(0, 'Average diet'), (1, 'No meat'), (2, 'No animal products'), (3, 'no carbs'), (4, 'no things younger than 10 thousand years'), (5, 'nothing apart from meat')], default=0),
        ),
    ]
