# Generated by Django 5.1 on 2024-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredient_list',
        ),
        migrations.AddField(
            model_name='product',
            name='Ingredient_list',
            field=models.ManyToManyField(related_name='used_in_products', to='nutrition_section.ingredient'),
        ),
    ]
