# Generated by Django 5.1 on 2024-09-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_section', '0002_remove_product_ingredient_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredient_list',
        ),
    ]
