# Generated by Django 5.1.1 on 2025-02-10 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
