# Generated by Django 5.1.1 on 2025-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_confirmationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foods_on_menu',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
