# Generated by Django 5.1.1 on 2025-02-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_restaurant_foods_on_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foods_on_menu',
            field=models.IntegerField(default=0),
        ),
    ]
