# Generated by Django 5.1.1 on 2025-02-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_restaurant_foods_on_menu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirmationtoken',
            table='ConfirmationTokens',
        ),
        migrations.AlterModelTable(
            name='food',
            table='Foods',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingredients',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurants',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
