# Generated by Django 5.1.1 on 2025-02-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exact_locations', to='core.restaurant')),
            ],
            options={
                'db_table': 'ExactLocations',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('restaurants', models.ManyToManyField(related_name='locations', to='core.restaurant')),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
    ]
