# Generated by Django 5.1.1 on 2025-02-16 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='approved_supervisors',
            field=models.ManyToManyField(blank=True, related_name='approved_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
