# Generated by Django 5.1.1 on 2025-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_food_approved_supervisors_food_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_approved',
        ),
    ]
