# Generated by Django 5.1.6 on 2025-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_foodchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodchange',
            name='new_calories',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
