# Generated by Django 5.1.6 on 2025-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_food_calories_foodchange_new_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchange',
            name='is_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
