# Generated by Django 5.1.1 on 2025-02-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_foodchange_is_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodchange',
            name='old_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_versions', to='core.food'),
        ),
    ]
