# Generated by Django 5.1.1 on 2025-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_foodchange_old_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='foodchange',
            name='new_serving_size',
            field=models.IntegerField(default=100),
        ),
    ]
