# Generated by Django 5.1.1 on 2025-02-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_food_serving_size_foodchange_new_serving_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
    ]
