# Generated by Django 5.1.6 on 2025-02-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_food_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodchange',
            name='new_calories',
        ),
    ]
