# Generated by Django 5.1.6 on 2025-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_foodchange_new_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodchange',
            name='new_name',
            field=models.CharField(max_length=255),
        ),
    ]
