# Generated by Django 5.1.1 on 2025-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_foodchange_new_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='approved_supervisors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodchange',
            name='new_approved_supervisors_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
