# Generated by Django 5.1.1 on 2025-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_foodchange_new_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=255),
        ),
    ]
