# Generated by Django 5.1.1 on 2025-03-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ExactLocation',
        ),
    ]
