# Generated by Django 5.1.1 on 2025-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_location_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
