# Generated by Django 5.1.1 on 2025-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hazard_level',
            field=models.FloatField(default=0),
        ),
    ]
