# Generated by Django 5.1.1 on 2025-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_food_hazard_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchange',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
