# Generated by Django 5.1.1 on 2025-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_foodchange_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchange',
            name='date',
            field=models.DateTimeField(default='2025-03-05'),
        ),
    ]
