# Generated by Django 5.1.1 on 2025-03-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_foodchange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodchange',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_food_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodchange',
            name='date',
            field=models.DateTimeField(default='2025-03-06'),
        ),
    ]
