# Generated by Django 5.1.1 on 2025-03-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_food_created_by_foodchange_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodchange',
            name='new_hazard_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodchange',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodchange',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodchange',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
