# Generated by Django 5.1.1 on 2025-03-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_location_restaurants_location_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
    ]
