# Generated by Django 5.1.1 on 2025-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='hazard_level',
            field=models.IntegerField(choices=[(0, 'Safe'), (1, 'Minimal Risk'), (2, 'Mild Risk'), (3, 'Moderate Risk'), (4, 'High Risk')], default=0),
        ),
    ]
