# Generated by Django 5.1.1 on 2025-03-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_ingredient_hazard_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hazard_level',
            field=models.FloatField(default=0),
        ),
    ]
