# Generated by Django 5.1.1 on 2025-04-07 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_restaurant_hazard_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general_question', 'General Question'), ('account_issues', 'Account Issues'), ('food_data_questions', 'Food Data Questions'), ('restaurant_information', 'Restaurant Information'), ('report_a_bug', 'Report a Bug'), ('feature_request', 'Feature Request'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'db_table': 'SupportMessages',
                'ordering': ['-created_at'],
            },
        ),
    ]
